pipeline {
  agent {
    node {
      label 'docker-build-node'
    }
  }

  environment {
    npm_config_cache = "npm-cache"
    nexusAuth = credentials('jenkins-nexus-npm')
  }

  options {
    timestamps()
  }

  stages {
    stage('Build') {
      steps {

        echo 'Starting Docker Container'
        withDockerContainer(image: 'node:lts-slim') {
          sh '''
            cd website
            echo 'Installing dependencies'
            yarn install
            echo 'Building'
            yarn run build
          '''
        }

        echo 'Leaving Container'

        // echo 'Compressing Artifacts'
        // // Creates an XZ compressed archive
        // sh "tar cJfv storagedocs-${env.GIT_BRANCH}.tar.xz dist"
      }

      post {
        failure {
          slackSend channel: '#devops',
            color: 'bad',
            message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* FAILED :scream:"
        }
      }
    }
 
    stage('Deploy to storagedocs.xpxsirius.io') {
      steps {
        echo 'Managing S3'
        withAWS(credentials: 'jenkins-ecr', region: 'ap-southeast-2') {
        echo 'Deleting old files'
        s3Delete bucket: 'storagedocs.xpxsirius.io', path: './'

        echo 'Uploading new files'
        s3Upload bucket: 'storagedocs.xpxsirius.io', acl: 'PublicRead', file: 'website/build/xpx-dfms-devportal-docs/', sseAlgorithm: 'AES256'
      }

        echo 'Managing CloudFront'
        withAWS(credentials: 'jenkins-ecr') {
          echo 'Invalidating CloudFront'
          cfInvalidate distribution: 'E1FPI2FXWG6KT7', paths: ['/*']
        }
      }

      post {
        success {
          slackSend channel: '#devops',
            color: 'good',
            message: "Branch *${env.GIT_BRANCH}* Deployment of *${currentBuild.fullDisplayName}* completed successfully :100:\nAvailable at http://storagedocs.xpxsirius.io"
        }

        failure {
          slackSend channel: '#devops',
            color: 'bad',
            message: "Branch *${env.GIT_BRANCH}* Deployment of *${currentBuild.fullDisplayName}* FAILED :scream:"
        }
      }  
    }
  }
}
